### ISSUE TITLE
Double click delay too short

### ISSUE THREAD

**Issue by Sasquire** [felixfong227/e621_helper_tampermonkey#3]
Chromium: 76.0 (Official Build) Arch Linux (64-bit)
Tampermonkey beta: 4.9
Desktop computer with mouse and keyboard

If I want to double click an image I have to click very quickly. Increasing the delay with Tocca would make this more comfortable.

**Comment by felixfong227** [comment]
🤔 U right, do you have any thoughts or idea about what should be your prefect timing?

I am actually thinking to make an ⚙️dashboard for users to play-around for themselves.

Thanks @Sasquire 🤗

**Comment by felixfong227** [comment]
Maybe I am going to config Tocca double click interval to 500ms 🤔
