### ISSUE TITLE
Like animation CORS issue

### ISSUE THREAD

**Issue by Sasquire** [felixfong227/e621_helper_tampermonkey#4]
Chromium: 76.0 (Official Build) Arch Linux (64-bit)
Tampermonkey beta: 4.9

Unfavoriting a post shows the heart break animation while favoriting an image gives
```
Access to XMLHttpRequest at 'https://assets5.lottiefiles.com/datafiles/d9bc9kYC2VttaKb/data.json' from origin 'https://e621.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by felixfong227** [comment]
Ahh, good old CORS issue 😒 

I see what you meant 👇  [Test Sauce](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fassets5.lottiefiles.com%2Fdatafiles%2Fd9bc9kYC2VttaKb%2Fdata.json&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote)

![image](https://user-images.githubusercontent.com/13918481/64763636-039bac80-d573-11e9-80d8-65bc2e42bddc.png)

Thanks for reporting the issue 😸  Gonna to fix it ASAP

**Comment by felixfong227** [comment]
Commit: d90ac78b7289076f0b4c6eda4cfd4a2c96fa64bc should fix the Lottie data file CORS issue.

Gonna close this issue for now if for some bizarre the issue still acute please do re-open this very issue 😄
